apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: platform-manifests
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-wave: "10"
spec:
  project: default
  source:
    repoURL: https://github.com/OutSora/unieats.git
    targetRevision: main
    path: platform/k8s
    directory: {recurse: true}
  destination:
    server: https://kubernetes.default.svc
    namespace: unieats
  syncPolicy:
    automated: {prune: true, selfHeal: true}
    syncOptions: [CreateNamespace=true]

