apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: kube-prometheus-stack
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://prometheus-community.github.io/helm-charts
    chart: kube-prometheus-stack
    targetRevision: 77.11.0
    helm:
      values: |
        grafana:
          service:
            type: ClusterIP
          sidecar:
            dashboards:
              enabled: true
              searchNamespace: ALL
          additionalDataSources:
            - name: Loki
              type: loki
              url: http://loki-gateway.observability.svc.cluster.local
            - name: Tempo
              type: tempo
              url: http://tempo.observability.svc.cluster.local:3100
        prometheus:
          prometheusSpec:
            serviceMonitorSelectorNilUsesHelmValues: false
            podMonitorSelectorNilUsesHelmValues: false
            ruleSelectorNilUsesHelmValues: false
            retention: 7d
  destination:
    server: https://kubernetes.default.svc
    namespace: observability
  syncPolicy:
    automated: {prune: true, selfHeal: true}
    syncOptions: [CreateNamespace=true]

