global:
  image:
    repository: host.minikube.internal:5000/unieats-services
    tag: dev
    pullPolicy: IfNotPresent
  kafkaBootstrapServers: unieats-kafka-bootstrap.kafka.svc.cluster.local:9092
  redisUrl: redis://valkey:6379

services:
  identity:
    module: identity
    port: 8001
    replicas: 1
  catalog:
    module: catalog
    port: 8002
    replicas: 2
  order:
    module: order
    port: 8003
    replicas: 2
  kitchen:
    module: kitchen
    port: 8004
    replicas: 1
  notification:
    module: notification
    port: 8005
    replicas: 1
  analytics:
    module: analytics
    port: 8006
    replicas: 1

resources:
  requests: {cpu: 50m, memory: 96Mi}
  limits: {cpu: 500m, memory: 256Mi}

autoscaling:
  enabled: true
  minReplicas: 2
  maxReplicas: 8
  targetCPUUtilizationPercentage: 65

dataStores:
  enabled: true
  storage: 2Gi
